//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ReportWriterTemplate {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.Bookmark bookmark_BulletTests;
        
        internal Microsoft.Office.Tools.Word.Bookmark bookmark_Orientation;
        
        internal Microsoft.Office.Tools.Word.Bookmark bookmark_Standards_Protocols;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        internal Microsoft.Office.Tools.Word.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckedListBox List_TestedStandards;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_ETCAssembled;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_CustAssembled;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox text_JobNumber;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_TF;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_SF;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_F;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_EX;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_TR;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_SC;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_AC;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_EX;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_TR;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_SC;
        
        internal Microsoft.Office.Tools.Word.Controls.CheckBox checkBox_AC;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_F;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_SF;
        
        internal Microsoft.Office.Tools.Word.Controls.NumericUpDown numericUpDown_TF;
        
        internal Microsoft.Office.Tools.Word.Controls.TextBox textBox_SystemName;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.bookmark_BulletTests.BeginInit();
            this.bookmark_Orientation.BeginInit();
            this.bookmark_Standards_Protocols.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.bookmark_Standards_Protocols.EndInit();
            this.bookmark_Orientation.EndInit();
            this.bookmark_BulletTests.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.bookmark_BulletTests = Globals.Factory.CreateBookmark(null, null, "bookmark_BulletTests", "bookmark_BulletTests", this);
            this.bookmark_Orientation = Globals.Factory.CreateBookmark(null, null, "bookmark_Orientation", "bookmark_Orientation", this);
            this.bookmark_Standards_Protocols = Globals.Factory.CreateBookmark(null, null, "bookmark_Standards_Protocols", "bookmark_Standards_Protocols", this);
            this.button1 = new Microsoft.Office.Tools.Word.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1B38A393A1E4D4142711A0011802FFCE2CD591", "1B38A393A1E4D4142711A0011802FFCE2CD591", this, "button1");
            this.List_TestedStandards = new Microsoft.Office.Tools.Word.Controls.CheckedListBox(Globals.Factory, this.ItemProvider, this.HostContext, "2AD38940E2458A2440D28CF22B4F4B49AB16E2", "2AD38940E2458A2440D28CF22B4F4B49AB16E2", this, "List_TestedStandards");
            this.checkBox_ETCAssembled = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "1199140AC1E9861448B1ACCE149CED6A6B07A1", "1199140AC1E9861448B1ACCE149CED6A6B07A1", this, "checkBox_ETCAssembled");
            this.checkBox_CustAssembled = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "19E53EFD21519C14AFF1A2C513BB9E404BD2F1", "19E53EFD21519C14AFF1A2C513BB9E404BD2F1", this, "checkBox_CustAssembled");
            this.text_JobNumber = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "0130FCDA509977043B00BA5B084FF89FE847B0", "0130FCDA509977043B00BA5B084FF89FE847B0", this, "text_JobNumber");
            this.checkBox_TF = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6767EC5746E5AB64BD86BF82640011F7522806", "6767EC5746E5AB64BD86BF82640011F7522806", this, "checkBox_TF");
            this.checkBox_SF = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "8FEE551F4818B684B248A2058F48C61E76CF88", "8FEE551F4818B684B248A2058F48C61E76CF88", this, "checkBox_SF");
            this.checkBox_F = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "47C93D2214177D445AD4878047FF34F169DD54", "47C93D2214177D445AD4878047FF34F169DD54", this, "checkBox_F");
            this.numericUpDown_EX = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1ECAEDBAE18A1914DE119055199CAF8D8A46E1", "1ECAEDBAE18A1914DE119055199CAF8D8A46E1", this, "numericUpDown_EX");
            this.numericUpDown_TR = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1E4F8EA28183D0141751B14E17D590A9D1D461", "1E4F8EA28183D0141751B14E17D590A9D1D461", this, "numericUpDown_TR");
            this.numericUpDown_SC = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1830908FD1B92814DBE1A70417EBCAAD1AC441", "1830908FD1B92814DBE1A70417EBCAAD1AC441", this, "numericUpDown_SC");
            this.numericUpDown_AC = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1686B98AE1E90114C43199D91268B701116AA1", "1686B98AE1E90114C43199D91268B701116AA1", this, "numericUpDown_AC");
            this.checkBox_EX = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "6B6D360786159364F8669E83699F5F1C3101A6", "6B6D360786159364F8669E83699F5F1C3101A6", this, "checkBox_EX");
            this.checkBox_TR = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "460D3425241AE0448064B6144E6288695844E4", "460D3425241AE0448064B6144E6288695844E4", this, "checkBox_TR");
            this.checkBox_SC = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "97CD4EDAA9B95F94F899A139991A5AC35327E9", "97CD4EDAA9B95F94F899A139991A5AC35327E9", this, "checkBox_SC");
            this.checkBox_AC = new Microsoft.Office.Tools.Word.Controls.CheckBox(Globals.Factory, this.ItemProvider, this.HostContext, "37BDF0CB7308663436239DCC3BD7FA2EEDB213", "37BDF0CB7308663436239DCC3BD7FA2EEDB213", this, "checkBox_AC");
            this.numericUpDown_F = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1C780D0FF13249141CD188E8120899D23F54F1", "1C780D0FF13249141CD188E8120899D23F54F1", this, "numericUpDown_F");
            this.numericUpDown_SF = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1A3D3C45B1F9E6149D218FC6170250DAA4C851", "1A3D3C45B1F9E6149D218FC6170250DAA4C851", this, "numericUpDown_SF");
            this.numericUpDown_TF = new Microsoft.Office.Tools.Word.Controls.NumericUpDown(Globals.Factory, this.ItemProvider, this.HostContext, "1B2AD3F281AA2E14BF11A11C14E4423D208931", "1B2AD3F281AA2E14BF11A11C14E4423D208931", this, "numericUpDown_TF");
            this.textBox_SystemName = new Microsoft.Office.Tools.Word.Controls.TextBox(Globals.Factory, this.ItemProvider, this.HostContext, "192AE2D6D1FFB314A3719F181232946BFBC671", "192AE2D6D1FFB314A3719F181232946BFBC671", this, "textBox_SystemName");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_EX)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_TR)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_SC)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_AC)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_F)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_SF)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_TF)).BeginInit();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.Control;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Name = "button1";
            this.button1.Text = "Write Report";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // List_TestedStandards
            // 
            this.List_TestedStandards.Items.AddRange(new object[] {
                        "Protocol",
                        "F1717",
                        "F2077"});
            this.List_TestedStandards.Name = "List_TestedStandards";
            // 
            // checkBox_ETCAssembled
            // 
            this.checkBox_ETCAssembled.Name = "checkBox_ETCAssembled";
            this.checkBox_ETCAssembled.Text = "ETC";
            this.checkBox_ETCAssembled.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_CustAssembled
            // 
            this.checkBox_CustAssembled.Name = "checkBox_CustAssembled";
            this.checkBox_CustAssembled.Text = "Customer";
            this.checkBox_CustAssembled.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // text_JobNumber
            // 
            this.text_JobNumber.Name = "text_JobNumber";
            this.text_JobNumber.Text = "123456";
            this.text_JobNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // checkBox_TF
            // 
            this.checkBox_TF.Name = "checkBox_TF";
            this.checkBox_TF.Text = "TF";
            this.checkBox_TF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_SF
            // 
            this.checkBox_SF.Name = "checkBox_SF";
            this.checkBox_SF.Text = "SF";
            this.checkBox_SF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_F
            // 
            this.checkBox_F.Name = "checkBox_F";
            this.checkBox_F.Text = "F";
            this.checkBox_F.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDown_EX
            // 
            this.numericUpDown_EX.Enabled = false;
            this.numericUpDown_EX.Name = "numericUpDown_EX";
            this.numericUpDown_EX.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // numericUpDown_TR
            // 
            this.numericUpDown_TR.Enabled = false;
            this.numericUpDown_TR.Name = "numericUpDown_TR";
            this.numericUpDown_TR.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // numericUpDown_SC
            // 
            this.numericUpDown_SC.Enabled = false;
            this.numericUpDown_SC.Name = "numericUpDown_SC";
            this.numericUpDown_SC.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // numericUpDown_AC
            // 
            this.numericUpDown_AC.Enabled = false;
            this.numericUpDown_AC.Name = "numericUpDown_AC";
            this.numericUpDown_AC.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // checkBox_EX
            // 
            this.checkBox_EX.Name = "checkBox_EX";
            this.checkBox_EX.Text = "EX";
            this.checkBox_EX.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_TR
            // 
            this.checkBox_TR.Name = "checkBox_TR";
            this.checkBox_TR.Text = "TR";
            this.checkBox_TR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_SC
            // 
            this.checkBox_SC.Name = "checkBox_SC";
            this.checkBox_SC.Text = "SC";
            this.checkBox_SC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // checkBox_AC
            // 
            this.checkBox_AC.Name = "checkBox_AC";
            this.checkBox_AC.Text = "AC";
            this.checkBox_AC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDown_F
            // 
            this.numericUpDown_F.Enabled = false;
            this.numericUpDown_F.Name = "numericUpDown_F";
            this.numericUpDown_F.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // numericUpDown_SF
            // 
            this.numericUpDown_SF.Enabled = false;
            this.numericUpDown_SF.Name = "numericUpDown_SF";
            this.numericUpDown_SF.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // numericUpDown_TF
            // 
            this.numericUpDown_TF.Enabled = false;
            this.numericUpDown_TF.Name = "numericUpDown_TF";
            this.numericUpDown_TF.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // bookmark_BulletTests
            // 
            this.bookmark_BulletTests.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // bookmark_Orientation
            // 
            this.bookmark_Orientation.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // bookmark_Standards_Protocols
            // 
            this.bookmark_Standards_Protocols.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // textBox_SystemName
            // 
            this.textBox_SystemName.Name = "textBox_SystemName";
            this.textBox_SystemName.Text = "System Name";
            this.textBox_SystemName.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // ThisDocument
            // 
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_EX)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_TR)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_SC)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_AC)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_F)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_SF)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_TF)).EndInit();
            this.button1.BindingContext = this.BindingContext;
            this.List_TestedStandards.BindingContext = this.BindingContext;
            this.checkBox_ETCAssembled.BindingContext = this.BindingContext;
            this.checkBox_CustAssembled.BindingContext = this.BindingContext;
            this.text_JobNumber.BindingContext = this.BindingContext;
            this.checkBox_TF.BindingContext = this.BindingContext;
            this.checkBox_SF.BindingContext = this.BindingContext;
            this.checkBox_F.BindingContext = this.BindingContext;
            this.numericUpDown_EX.BindingContext = this.BindingContext;
            this.numericUpDown_TR.BindingContext = this.BindingContext;
            this.numericUpDown_SC.BindingContext = this.BindingContext;
            this.numericUpDown_AC.BindingContext = this.BindingContext;
            this.checkBox_EX.BindingContext = this.BindingContext;
            this.checkBox_TR.BindingContext = this.BindingContext;
            this.checkBox_SC.BindingContext = this.BindingContext;
            this.checkBox_AC.BindingContext = this.BindingContext;
            this.numericUpDown_F.BindingContext = this.BindingContext;
            this.numericUpDown_SF.BindingContext = this.BindingContext;
            this.numericUpDown_TF.BindingContext = this.BindingContext;
            this.textBox_SystemName.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.bookmark_Standards_Protocols.Dispose();
            this.bookmark_Orientation.Dispose();
            this.bookmark_BulletTests.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
